# https://taskfile.dev

version: '3'

vars:
  HOOKS_DIR: .githooks

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list
    silent: true

  setup:
    desc: "Complete setup: check prerequisites and configure Git hooks"
    deps:
      - check-commitlint
      - setup-hooks

  check-commitlint:
    desc: "Check if commitlint is installed globally"
    cmds:
      - |
        if ! command -v commitlint >/dev/null 2>&1; then
          echo "❌ commitlint is not installed globally"
          echo ""
          echo "Install it with:"
          echo "  npm install -g @commitlint/cli @commitlint/config-conventional"
          echo ""
          exit 1
        else
          echo "✅ commitlint is installed"
          commitlint --version
        fi
    silent: true

  install-commitlint:
    desc: "Install commitlint globally"
    cmds:
      - npm install -g @commitlint/cli @commitlint/config-conventional
      - echo "✅ commitlint installed successfully"
    silent: true

  setup-hooks:
    desc: "Configure Git hooks (make executable and set hooks path)"
    cmds:
      - |
        echo "Setting up Git hooks..."
        
        # Make hooks executable
        chmod +x {{.HOOKS_DIR}}/commit-msg
        chmod +x {{.HOOKS_DIR}}/prepare-commit-msg
        echo "✅ Hooks are now executable"
        
        # Configure Git to use the custom hooks directory
        git config core.hooksPath {{.HOOKS_DIR}}
        echo "✅ Git configured to use {{.HOOKS_DIR}}"
        
        echo ""
        echo "Active hooks:"
        ls -lh {{.HOOKS_DIR}}/
        echo ""
        echo "🎉 Git hooks setup complete!"
    silent: true

  disable-hooks:
    desc: "Disable Git hooks"
    cmds:
      - git config --unset core.hooksPath
      - echo "✅ Git hooks disabled"
    silent: true

  test-commit:
    desc: "Test commitlint with sample messages"
    cmds:
      - |
        echo "Testing commitlint..."
        echo ""
        
        echo "❌ Testing invalid message:"
        echo "invalid message" | commitlint || echo "  (Expected to fail)"
        echo ""
        
        echo "✅ Testing valid message:"
        echo "feat: add new feature" | commitlint && echo "  (Passed!)"
        echo ""
        
        echo "✅ Testing valid message with scope:"
        echo "fix(api): correct bug" | commitlint && echo "  (Passed!)"
    silent: true
